name: Haskell CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Stack
        run: |
          curl -sSL https://get.haskellstack.org/ | sh -s - -f

      - name: Start build
        run: stack build
        
      - name: Start tests
        run: stack test
